trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SERVICEBUS_CONNECTION_STRING: $(AZURE_SERVICEBUS_CONNECTION_STRING)
  ORDER_QUEUE_NAME: orders

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install Dependencies and Build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '82ab74c6-4804-4b16-adbf-17b449458ed5'
    appType: 'webAppLinux'
    appName: 'myapp-web-dev'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app.zip'
